spring:
  cloud:
    gateway:
      routes:
        - id: vaccinumF-appointment
          uri: lb://vaccinumF-appointment
          predicates:
            - Path=/appoint/**,/appointment/**

        - id: vaccinumF-vaccinum
          uri: lb://vaccinumF-vaccinum
          predicates:
            - Path=/vaccinum/**,/vaccinum_type/**,

        - id: vaccinumF-user
          uri: lb://vaccinumF-user
          predicates:
            - Path=/user/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        gateway:
          globalcors: # 全局跨域处理
            add-to-simple-url-handler-mapping: true # 解决 options 请求被拦截问题
            cors-configurations:
              '[/**]':
                allowedOrigins: # 允许哪些网站的跨域请求
                  - "http://localhost:8080"
                allowedMethods: # 允许的跨域请求方法
                  - "GET"
                  - "POST"
                  - "DELETE"
                  - "PUT"
                  - "OPTIONS"
                allowedHeaders: "*" # 允许跨域请求中携带的请求头：全部
                allowCredentials: true  # 是否允许携带 cookie
                maxAge: 360000  # 跨域检测的有效期
  application:
    name: vecisystem-gateway
  resources:
    static-locations: file:E:\\upload\\,classpath:/static/
server:
  port: 88
